// Simple and friendly word bank for typing practice
export const WORD_BANK = [
  // Special locations
  "Bangladesh", "Moulvibazar", "Sylhet", "Dhaka", "Chittagong",
  
  // Common words (1-100)
  "the", "be", "to", "of", "and", "a", "in", "that", "have", "I",
  "it", "for", "not", "on", "with", "he", "as", "you", "do", "at",
  "this", "but", "his", "by", "from", "they", "we", "say", "her", "she",
  "or", "an", "will", "my", "one", "all", "would", "there", "their", "what",
  
  // Common words (101-300)
  "so", "up", "out", "if", "about", "who", "get", "which", "go", "me",
  "when", "make", "can", "like", "time", "no", "just", "him", "know", "take",
  "people", "into", "year", "your", "good", "some", "could", "them", "see", "other",
  "than", "then", "now", "look", "only", "come", "its", "over", "think", "also",
  "back", "after", "use", "two", "how", "our", "work", "first", "well", "way",
  "even", "new", "want", "because", "any", "these", "give", "day", "most", "us",
  
  // Technology & Digital
  "computer", "internet", "website", "software", "hardware", "program", "code", "data",
  "digital", "online", "email", "password", "user", "system", "network", "server",
  "mobile", "app", "download", "upload", "cloud", "file", "folder", "document",
  "keyboard", "mouse", "screen", "monitor", "laptop", "desktop", "tablet", "phone",
  "technology", "innovation", "algorithm", "database", "interface", "platform", "browser",
  
  // Education & Learning
  "learn", "study", "school", "student", "teacher", "education", "class", "lesson",
  "knowledge", "skill", "practice", "training", "course", "subject", "exam", "test",
  "university", "college", "degree", "graduate", "research", "library", "book", "read",
  "write", "understand", "remember", "focus", "concentrate", "improve", "develop",
  
  // Business & Work
  "business", "company", "work", "job", "career", "office", "manager", "employee",
  "team", "project", "meeting", "client", "customer", "service", "product", "market",
  "sale", "profit", "revenue", "budget", "finance", "investment", "strategy", "plan",
  "goal", "target", "success", "growth", "development", "innovation", "quality",
  
  // Communication
  "talk", "speak", "tell", "ask", "answer", "question", "discuss", "explain",
  "communicate", "conversation", "message", "information", "news", "report", "story",
  "language", "word", "sentence", "meaning", "express", "share", "connect", "contact",
  
  // Time & Dates
  "today", "tomorrow", "yesterday", "week", "month", "year", "hour", "minute",
  "second", "morning", "afternoon", "evening", "night", "day", "time", "moment",
  "past", "present", "future", "early", "late", "soon", "now", "then", "when",
  "always", "never", "sometimes", "often", "usually", "rarely", "frequently",
  
  // Actions & Verbs
  "run", "walk", "jump", "sit", "stand", "move", "stop", "start", "begin", "end",
  "open", "close", "push", "pull", "lift", "drop", "throw", "catch", "hold", "carry",
  "build", "create", "make", "design", "develop", "produce", "construct", "form",
  "break", "fix", "repair", "maintain", "improve", "change", "transform", "modify",
  "increase", "decrease", "grow", "reduce", "expand", "shrink", "rise", "fall",
  
  // Descriptive Words
  "good", "bad", "great", "excellent", "perfect", "wonderful", "amazing", "fantastic",
  "beautiful", "ugly", "pretty", "handsome", "attractive", "nice", "pleasant", "lovely",
  "big", "small", "large", "tiny", "huge", "enormous", "massive", "gigantic", "little",
  "long", "short", "tall", "high", "low", "deep", "shallow", "wide", "narrow", "thick",
  "fast", "slow", "quick", "rapid", "swift", "gradual", "sudden", "immediate",
  "hot", "cold", "warm", "cool", "freezing", "boiling", "mild", "moderate",
  "bright", "dark", "light", "dim", "shiny", "dull", "clear", "cloudy", "transparent",
  
  // Nature & Environment
  "nature", "environment", "earth", "world", "planet", "sky", "sun", "moon", "star",
  "water", "ocean", "sea", "river", "lake", "stream", "rain", "snow", "ice", "cloud",
  "mountain", "hill", "valley", "forest", "tree", "plant", "flower", "grass", "leaf",
  "animal", "bird", "fish", "insect", "wildlife", "creature", "species", "habitat",
  "weather", "climate", "temperature", "season", "spring", "summer", "autumn", "winter",
  
  // Food & Drink
  "food", "eat", "drink", "meal", "breakfast", "lunch", "dinner", "snack", "dessert",
  "fruit", "vegetable", "meat", "fish", "bread", "rice", "pasta", "cheese", "egg",
  "milk", "water", "juice", "coffee", "tea", "soda", "wine", "beer", "alcohol",
  "sweet", "sour", "bitter", "salty", "spicy", "delicious", "tasty", "yummy", "fresh",
  "cook", "bake", "fry", "boil", "grill", "roast", "steam", "prepare", "serve",
  
  // Health & Body
  "health", "healthy", "fit", "strong", "weak", "sick", "ill", "disease", "pain",
  "body", "head", "face", "eye", "ear", "nose", "mouth", "tooth", "tongue", "neck",
  "shoulder", "arm", "hand", "finger", "chest", "back", "stomach", "leg", "foot", "toe",
  "heart", "brain", "blood", "bone", "muscle", "skin", "hair", "nail", "organ",
  "doctor", "nurse", "hospital", "medicine", "treatment", "cure", "therapy", "surgery",
  
  // Emotions & Feelings
  "happy", "sad", "angry", "excited", "bored", "tired", "energetic", "calm", "nervous",
  "love", "hate", "like", "dislike", "enjoy", "prefer", "want", "need", "desire", "wish",
  "feel", "emotion", "mood", "attitude", "spirit", "mind", "heart", "soul", "passion",
  "joy", "sorrow", "fear", "courage", "hope", "despair", "confidence", "doubt", "trust",
  
  // Places & Locations
  "place", "location", "position", "area", "region", "zone", "district", "neighborhood",
  "city", "town", "village", "country", "nation", "state", "province", "capital",
  "home", "house", "apartment", "building", "room", "floor", "wall", "door", "window",
  "street", "road", "avenue", "highway", "path", "bridge", "tunnel", "station",
  "store", "shop", "market", "mall", "restaurant", "cafe", "hotel", "bank", "hospital",
  
  // Numbers & Quantities
  "one", "two", "three", "four", "five", "six", "seven", "eight", "nine", "ten",
  "many", "few", "several", "some", "all", "none", "most", "least", "more", "less",
  "much", "little", "enough", "plenty", "extra", "additional", "total", "whole", "part",
  "first", "second", "third", "last", "next", "previous", "following", "final",
  
  // Colors
  "color", "red", "blue", "green", "yellow", "orange", "purple", "pink", "brown", "black",
  "white", "gray", "silver", "gold", "beige", "tan", "navy", "turquoise", "violet",
  
  // Materials & Objects
  "thing", "object", "item", "stuff", "material", "substance", "element", "component",
  "metal", "wood", "plastic", "glass", "paper", "cloth", "fabric", "leather", "rubber",
  "stone", "rock", "sand", "dirt", "soil", "mud", "clay", "cement", "concrete",
  "tool", "equipment", "device", "machine", "instrument", "apparatus", "gadget",
  
  // More common verbs
  "find", "search", "discover", "explore", "investigate", "examine", "inspect", "observe",
  "watch", "see", "look", "view", "notice", "spot", "detect", "identify", "recognize",
  "hear", "listen", "sound", "noise", "music", "song", "voice", "speak", "talk", "say",
  "read", "write", "type", "print", "draw", "paint", "sketch", "design", "create",
  "play", "game", "sport", "exercise", "practice", "train", "compete", "win", "lose",
  
  // Social & Relationships
  "friend", "family", "parent", "mother", "father", "brother", "sister", "child", "baby",
  "husband", "wife", "partner", "couple", "relationship", "marriage", "wedding", "love",
  "person", "man", "woman", "boy", "girl", "adult", "teenager", "elder", "senior",
  "group", "community", "society", "public", "private", "social", "cultural", "tradition",
  
  // Abstract Concepts
  "idea", "thought", "concept", "theory", "principle", "rule", "law", "fact", "truth",
  "reason", "cause", "effect", "result", "consequence", "outcome", "impact", "influence",
  "problem", "solution", "issue", "challenge", "difficulty", "obstacle", "barrier",
  "opportunity", "chance", "possibility", "option", "choice", "decision", "selection",
  "purpose", "goal", "aim", "objective", "target", "mission", "vision", "dream",
  "value", "worth", "importance", "significance", "meaning", "sense", "point", "matter",
  
  // More adjectives
  "new", "old", "young", "ancient", "modern", "contemporary", "current", "recent",
  "easy", "hard", "difficult", "simple", "complex", "complicated", "challenging",
  "important", "significant", "major", "minor", "main", "primary", "secondary", "key",
  "real", "fake", "true", "false", "actual", "virtual", "genuine", "authentic",
  "possible", "impossible", "probable", "likely", "unlikely", "certain", "uncertain",
  "necessary", "essential", "vital", "crucial", "critical", "important", "optional",
  
  // Additional common words
  "very", "really", "quite", "rather", "pretty", "fairly", "extremely", "incredibly",
  "almost", "nearly", "practically", "virtually", "basically", "essentially", "mainly",
  "especially", "particularly", "specifically", "generally", "usually", "normally",
  "already", "yet", "still", "again", "once", "twice", "thrice", "forever", "never",
  "here", "there", "everywhere", "nowhere", "somewhere", "anywhere", "where", "wherever",
  "yes", "no", "maybe", "perhaps", "probably", "definitely", "certainly", "absolutely",
  
  // Extended vocabulary
  "ability", "access", "account", "achieve", "action", "active", "activity", "actual",
  "address", "admit", "adult", "advance", "advantage", "advice", "affect", "afford",
  "afraid", "agree", "ahead", "allow", "almost", "alone", "along", "already", "although",
  "amazing", "amount", "ancient", "anger", "angle", "animal", "announce", "annual",
  "another", "answer", "anyone", "anything", "anyway", "anywhere", "apart", "appear",
  "apple", "apply", "approach", "appropriate", "approve", "area", "argue", "arise",
  "around", "arrange", "arrest", "arrive", "article", "artist", "aside", "aspect",
  "assess", "assign", "assist", "associate", "assume", "assure", "attach", "achieve",
  "attempt", "attend", "attention", "attitude", "attract", "audience", "author",
  "authority", "automatic", "available", "average", "avoid", "award", "aware", "away",
  
  "balance", "ball", "band", "bank", "bar", "base", "basic", "basis", "battle",
  "beach", "bear", "beat", "beautiful", "beauty", "become", "bed", "before", "begin",
  "behavior", "behind", "being", "belief", "believe", "bell", "belong", "below",
  "belt", "bench", "bend", "beneath", "benefit", "beside", "besides", "best", "better",
  "between", "beyond", "bill", "bind", "birth", "bit", "bite", "bitter", "blame",
  "blank", "blind", "block", "blood", "blow", "board", "boat", "bone", "border",
  "born", "borrow", "both", "bother", "bottle", "bottom", "bound", "bowl", "box",
  "brain", "branch", "brand", "brave", "bread", "break", "breath", "breathe", "breed",
  "brief", "bright", "brilliant", "bring", "broad", "broken", "brush", "budget",
  "burn", "burst", "bury", "button", "buyer",
  
  "cable", "cake", "calculate", "call", "camera", "camp", "campaign", "campus",
  "cancel", "cancer", "candidate", "capable", "capacity", "capital", "captain",
  "capture", "carbon", "card", "care", "careful", "carefully", "carrier", "case",
  "cash", "cast", "cat", "catch", "category", "cause", "ceiling", "celebrate",
  "cell", "center", "central", "century", "ceremony", "certain", "certainly",
  "chain", "chair", "chairman", "challenge", "chamber", "champion", "chance",
  "channel", "chapter", "character", "characteristic", "charge", "charity", "chart",
  "chase", "cheap", "check", "cheek", "chemical", "chest", "chicken", "chief",
  "childhood", "chip", "chocolate", "choice", "choose", "church", "cigarette",
  "circle", "circumstance", "citizen", "civil", "claim", "classic", "classroom",
  "clean", "clear", "clearly", "client", "climate", "climb", "clock", "closely",
  "closer", "clothes", "clothing", "club", "clue", "coach", "coal", "coast", "coat",
  "code", "coffee", "cold", "collapse", "colleague", "collect", "collection",
  "college", "color", "column", "combination", "combine", "comfort", "comfortable",
  "command", "comment", "commercial", "commission", "commit", "commitment",
  "committee", "common", "communicate", "communication", "community", "company",
  "compare", "comparison", "compete", "competition", "competitive", "competitor",
  "complain", "complaint", "complete", "completely", "complex", "complicated",
  "component", "compose", "composition", "comprehensive", "computer", "concentrate",
  "concentration", "concept", "concern", "concerned", "concert", "conclude",
  "conclusion", "concrete", "condition", "conduct", "conference", "confidence",
  "confident", "confirm", "conflict", "confront", "confusion", "congress",
  "connect", "connection", "conscious", "consciousness", "consensus", "consequence",
  "conservative", "consider", "considerable", "consideration", "consist", "consistent",
  "constant", "constantly", "constitute", "constitutional", "construct", "construction",
  "consultant", "consume", "consumer", "contact", "contain", "container", "contemporary",
  "content", "contest", "context", "continue", "continued", "contract", "contrast",
  "contribute", "contribution", "control", "controversial", "controversy", "convention",
  "conventional", "conversation", "convert", "convince", "cook", "cookie", "cooking",
  "cool", "cooperation", "cope", "copy", "core", "corn", "corner", "corporate",
  "corporation", "correct", "correspondent", "cost", "cotton", "couch", "could",
  "council", "count", "counter", "country", "county", "couple", "courage", "course",
  "court", "cousin", "cover", "coverage", "cow", "crack", "craft", "crash", "crazy",
  "cream", "create", "creation", "creative", "creature", "credit", "crew", "cricket",
  "crisis", "criteria", "critic", "critical", "criticism", "criticize",
  "crop", "cross", "crowd", "crucial", "cry", "cultural", "culture", "cup", "curious",
  "current", "currently", "curriculum", "custom", "customer", "cycle",
  
  "dad", "daily", "damage", "dance", "danger", "dangerous", "dare", "dark",
  "darkness", "date", "daughter", "dawn", "deal", "dealer", "dear",
  "debate", "debt", "decade", "decide", "decision", "deck", "declare",
  "decline", "decrease", "deep", "deeply", "deer", "defeat", "defend", "defendant",
  "defense", "defensive", "deficit", "define", "definitely", "definition", "degree",
  "delay", "deliver", "delivery", "demand", "democracy", "democratic", "demonstrate",
  "demonstration", "deny", "department", "depend", "dependent", "depending", "depict",
  "depression", "depth", "deputy", "derive", "describe", "description", "desert",
  "deserve", "designer", "desire", "desk", "desperate", "despite", "destroy",
  "destruction", "detail", "detailed", "detect", "determine", "develop", "developing",
  "device", "devote", "dialogue", "die", "diet", "differ", "difference", "different",
  "differently", "difficult", "difficulty", "dig", "digital", "dimension", "dining",
  "dinner", "direct", "direction", "directly", "director", "dirt", "dirty",
  "disability", "disagree", "disappear", "disaster", "discipline", "discourse",
  "discover", "discovery", "discrimination", "discuss", "discussion", "disease",
  "dish", "dismiss", "disorder", "display", "dispute", "distance", "distant",
  "distinct", "distinction", "distinguish", "distribute", "distribution", "district",
  "diverse", "diversity", "divide", "division", "divorce", "doctor", "doctrine",
  "document", "dog", "domestic", "dominant", "dominate", "door", "double", "doubt",
  "downtown", "dozen", "draft", "drag", "drama", "dramatic", "dramatically", "draw",
  "drawing", "dream", "dress", "drink", "drive", "driver", "drop", "drug", "dry",
  "due", "during", "dust", "duty", "dynamic",
  
  "each", "eager", "earn", "earnings", "earth", "ease", "easily", "east", "eastern",
  "easy", "economic", "economics", "economist", "economy", "edge", "edition", "editor",
  "educate", "educational", "educator", "effect", "effective", "effectively",
  "efficiency", "efficient", "effort", "eight", "eighteen", "eighth", "eighty",
  "either", "elderly", "elect", "election", "electric", "electricity", "electronic",
  "elegant", "elementary", "elephant", "eleven", "eliminate", "elite", "else",
  "elsewhere", "embrace", "emerge", "emergency", "emission", "emotion", "emotional",
  "emphasis", "emphasize", "employ", "employee", "employer", "employment", "empty",
  "enable", "encounter", "encourage", "enemy", "energy", "enforcement", "engage",
  "engine", "engineer", "engineering", "enhance", "enjoy", "enormous", "ensure",
  "enter", "enterprise", "entertainment", "enthusiasm", "entire", "entirely",
  "entrance", "entry", "envelope", "environmental", "episode", "equal", "equally",
  "equipment", "era", "error", "escape", "especially", "essay", "essential",
  "essentially", "establish", "establishment", "estate", "estimate", "ethics",
  "ethnic", "evaluate", "evaluation", "even", "evening", "event", "eventually",
  "ever", "every", "everybody", "everyday", "everyone", "everything", "everywhere",
  "evidence", "evolution", "evolve", "exact", "exactly", "examination", "examine",
  "example", "exceed", "excellent", "except", "exception", "exchange", "exciting",
  "exclude", "exclusive", "excuse", "executive", "exercise", "exhibit", "exhibition",
  "exist", "existence", "existing", "exit", "expand", "expansion", "expect",
  "expectation", "expense", "expensive", "experience", "experienced", "experiment",
  "experimental", "expert", "explain", "explanation", "explode", "explore", "explosion",
  "export", "expose", "exposure", "express", "expression", "extend", "extension",
  "extensive", "extent", "external", "extra", "extraordinary", "extreme", "extremely",
  
  "fabric", "face", "facility", "facing", "factor", "factory", "faculty", "fade",
  "fail", "failure", "fair", "fairly", "faith", "fall", "false", "familiar",
  "famous", "fan", "fantasy", "far", "farm", "farmer", "fashion", "fast", "fat",
  "fate", "father", "fault", "favor", "favorite", "fear", "feature", "federal",
  "fee", "feed", "feel", "feeling", "fellow", "female", "fence", "festival",
  "fewer", "fiber", "fiction", "field", "fifteen", "fifth", "fifty", "fight",
  "fighter", "fighting", "figure", "file", "fill", "film", "final", "finally",
  "finance", "financial", "financing", "finding", "fine", "finger", "finish",
  "fire", "firm", "firmly", "fish", "fishing", "fit", "fitness", "five", "fix",
  "flag", "flame", "flat", "flavor", "flee", "flesh", "flight", "float", "flood",
  "floor", "flow", "flower", "fly", "focus", "folk", "follow", "following", "food",
  "foot", "football", "force", "foreign", "forest", "forever", "forget", "form",
  "formal", "formation", "former", "formula", "forth", "fortune", "forty", "forum",
  "forward", "found", "foundation", "founder", "four", "fourteen", "fourth", "frame",
  "framework", "free", "freedom", "freeze", "French", "frequency", "frequent",
  "frequently", "fresh", "friend", "friendly", "friendship", "from", "front",
  "fruit", "frustration", "fuel", "full", "fully", "fun", "function", "functional",
  "fund", "fundamental", "funding", "funeral", "funny", "furniture", "furthermore",
  "future",
  
  "gain", "galaxy", "gallery", "game", "gang", "gap", "garage", "garden", "garlic",
  "gas", "gate", "gather", "gaze", "gear", "gender", "gene", "general", "generally",
  "generate", "generation", "genetic", "gentleman", "gently", "German", "gesture",
  "ghost", "giant", "gift", "gifted", "girl", "girlfriend", "given", "glad", "glance",
  "glass", "global", "glove", "goal", "God", "gold", "golden", "golf", "good",
  "government", "governor", "grab", "grace", "grade", "gradually", "graduate",
  "grain", "grand", "grandfather", "grandmother", "grant", "grass", "grateful",
  "grave", "gray", "great", "greatest", "greatly", "green", "grocery", "ground",
  "growing", "guarantee", "guard", "guess", "guest", "guidance", "guide", "guideline",
  "guilty", "guitar", "guy",
  
  "habit", "habitat", "hair", "half", "hall", "hand", "handful", "handle", "hang",
  "happen", "happily", "happiness", "harbor", "hardly", "harm", "hat", "hate",
  "have", "head", "headline", "headquarters", "heal", "health", "healthy", "heap",
  "hearing", "heat", "heaven", "heavily", "heavy", "heel", "height", "helicopter",
  "hell", "hello", "help", "helpful", "hence", "hero", "herself", "hesitate",
  "hide", "highly", "highway", "hill", "himself", "hint", "hip", "hire", "historic",
  "historical", "history", "hold", "hole", "holiday", "holy", "honest", "honey",
  "honor", "hope", "horizon", "horror", "horse", "hospital", "host", "hostage",
  "hostile", "hotel", "household", "housing", "however", "huge", "human", "humor",
  "hundred", "hungry", "hunter", "hunting", "hurt", "husband", "hypothesis",
  
  "ice", "idea", "ideal", "identification", "identify", "identity", "ideology",
  "ignore", "ill", "illegal", "illness", "illustrate", "image", "imagination",
  "imagine", "immediate", "immediately", "immigrant", "immigration", "impact",
  "implement", "implementation", "implication", "imply", "import", "importance",
  "impose", "impossible", "impress", "impression", "impressive", "improve",
  "improvement", "incentive", "incident", "include", "including", "income",
  "incorporate", "increase", "increased", "increasing", "increasingly", "incredible",
  "indeed", "independence", "independent", "index", "Indian", "indicate", "indication",
  "individual", "industrial", "industry", "infant", "infection", "inflation",
  "influence", "inform", "information", "ingredient", "initial", "initially",
  "initiative", "injury", "inner", "innocent", "innovation", "input", "inquiry",
  "inside", "insight", "insist", "inspire", "install", "instance", "instant",
  "instead", "institution", "institutional", "instruction", "instructor", "instrument",
  "insurance", "intellectual", "intelligence", "intend", "intense", "intensity",
  "intention", "interaction", "interest", "interested", "interesting", "internal",
  "international", "interpret", "interpretation", "intervention", "interview",
  "introduce", "introduction", "invasion", "invest", "investigate", "investigation",
  "investigator", "investor", "invitation", "invite", "involve", "involved",
  "involvement", "Iraqi", "Irish", "iron", "Islamic", "island", "Israeli", "issue",
  "Italian", "itself",
  
  "jacket", "jail", "Japanese", "jet", "Jew", "Jewish", "joint", "joke", "journal",
  "journalist", "journey", "joy", "judge", "judgment", "juice", "jump", "junior",
  "jury", "just", "justice", "justify",
  
  "keep", "key", "kick", "kind", "king", "kiss",
  "kitchen", "knee", "knife", "knock", "know", "knowledge", "known",
  
  "label", "labor", "laboratory", "lack", "lady", "lake", "land", "landscape",
  "language", "lap", "large", "largely", "last", "late", "later", "Latin", "latter",
  "laugh", "laughter", "launch", "lawyer", "layer", "lead", "leader", "leadership",
  "leading", "league", "lean", "learn", "learning", "least", "leather", "leave",
  "left", "legacy", "legal", "legend", "legislation", "legislative", "legitimate",
  "lemon", "length", "less", "lesson", "letter", "level", "liberal", "library",
  "license", "life", "lifestyle", "lifetime", "lift", "light", "lighting", "like",
  "likely", "limit", "limitation", "limited", "line", "link", "lion", "list",
  "listen", "literally", "literary", "literature", "little", "live", "living",
  "load", "loan", "local", "locate", "location", "lock", "long", "look", "loose",
  "lose", "loss", "lost", "loud", "love", "lovely", "lover", "lower", "luck",
  "lucky", "lunch", "lung", "luxury",
  
  "machine", "mad", "magazine", "magic", "mail", "main", "mainly", "maintain",
  "maintenance", "major", "majority", "maker", "makeup", "male", "mall", "mammal",
  "manage", "management", "manager", "manner", "manufacturer", "manufacturing",
  "manuscript", "margin", "marine", "mark", "marker", "marketing", "marriage",
  "married", "marry", "mask", "mass", "massive", "master", "match", "mate",
  "material", "math", "matter", "maximum", "mayor", "meal", "mean", "meaning",
  "meanwhile", "measure", "measurement", "meat", "mechanism", "media", "medical",
  "medication", "medicine", "medium", "meet", "meeting", "member", "membership",
  "memory", "mental", "mention", "menu", "mere", "merely", "mess", "message",
  "metal", "meter", "method", "Mexican", "middle", "might", "military", "milk",
  "million", "mind", "mine", "minister", "minor", "minority", "minute", "miracle",
  "mirror", "miss", "missile", "mission", "mistake", "mix", "mixture", "mode",
  "model", "moderate", "modern", "modest", "mom", "moment", "money", "monitor",
  "month", "mood", "moon", "moral", "moreover", "morning", "mortgage", "mostly",
  "mother", "motion", "motivation", "motor", "mount", "mountain", "mouse", "mouth",
  "movement", "movie", "multiple", "muscle", "museum", "music", "musical",
  "musician", "Muslim", "must", "mutual", "myself", "mystery", "myth",
  
  "naked", "name", "narrative", "narrow", "nation", "national", "native", "natural",
  "naturally", "nature", "near", "nearby", "nearly", "necessarily", "necessary",
  "neck", "need", "negative", "negotiate", "negotiation", "neighbor", "neighborhood",
  "neither", "nerve", "nervous", "nest", "network", "never", "nevertheless", "newly",
  "newspaper", "next", "nice", "night", "nine", "nineteen", "ninety", "nobody",
  "noise", "nomination", "none", "nonetheless", "nor", "norm", "normal", "normally",
  "north", "northern", "nose", "note", "nothing", "notice", "notion", "novel",
  "nowhere", "nuclear", "number", "numerous", "nurse", "nut",
  
  "object", "objective", "obligation", "observation", "observe", "observer",
  "obtain", "obvious", "obviously", "occasion", "occasionally", "occupation",
  "occupy", "occur", "ocean", "odd", "odds", "offense", "offensive", "offer",
  "offering", "officer", "official", "often", "okay", "Olympic", "once",
  "ongoing", "onion", "onto", "opening", "operate", "operating", "operation",
  "operator", "opinion", "opponent", "opportunity", "oppose", "opposed", "opposite",
  "opposition", "option", "orange", "order", "ordinary", "organic", "organization",
  "organize", "orientation", "origin", "original", "originally", "others", "otherwise",
  "ought", "ourselves", "outcome", "outside", "oven", "overall", "overcome",
  "overlook", "owe", "owner", "ownership", "oxygen",
  
  "pace", "pack", "package", "page", "pain", "painful", "paint", "painter",
  "painting", "pair", "pale", "Palestinian", "palm", "pan", "panel", "pant",
  "pants", "parent", "park", "parking", "parliament", "participant", "participate",
  "participation", "particular", "particularly", "partly", "partnership", "passage",
  "passenger", "passion", "past", "patch", "path", "patient", "pattern", "pause",
  "payment", "peace", "peak", "peer", "penalty", "people", "pepper", "perceive",
  "percentage", "perception", "perfect", "perfectly", "perform", "performance",
  "perhaps", "period", "permanent", "permission", "permit", "persist", "personal",
  "personality", "personally", "personnel", "perspective", "persuade", "pet",
  "phase", "phenomenon", "philosophy", "photograph", "photographer", "phrase",
  "physical", "physically", "physician", "piano", "pick", "picture", "piece",
  "pile", "pilot", "pine", "pink", "pipe", "pitch", "pizza", "placement", "plain",
  "plane", "planet", "planning", "plate", "player", "plea", "plead", "pleasant",
  "please", "pleasure", "plenty", "plot", "plus", "pocket", "poem", "poet",
  "poetry", "point", "pole", "police", "policy", "political", "politically",
  "politician", "politics", "poll", "pollution", "pool", "popular", "population",
  "porch", "port", "portion", "portrait", "portray", "pose", "position", "positive",
  "possess", "possibility", "possible", "possibly", "post", "pot", "potato",
  "potential", "potentially", "pound", "pour", "poverty", "powder", "powerful",
  "practical", "practically", "pray", "prayer", "precisely", "predict", "prefer",
  "preference", "pregnancy", "pregnant", "preparation", "prepare", "prescription",
  "presence", "presentation", "preserve", "presidency", "president", "presidential",
  "press", "pressing", "pressure", "pretend", "pretty", "prevent", "previous",
  "previously", "price", "pride", "priest", "primarily", "prime", "principal",
  "priority", "prison", "prisoner", "privacy", "prize", "probably", "procedure",
  "proceed", "processing", "producer", "profession", "professional", "professor",
  "profile", "progressive", "prohibit", "prominent", "promise", "promising",
  "promote", "prompt", "proof", "proper", "properly", "property", "proportion",
  "proposal", "propose", "proposed", "prosecutor", "prospect", "protect",
  "protection", "protein", "protest", "proud", "prove", "provider", "province",
  "provision", "psychological", "psychologist", "psychology", "publicly", "publish",
  "publisher", "pull", "punishment", "purchase", "pure", "purple", "pursue",
  "push", "puzzle",
  
  "qualify", "quality", "quarter", "quarterback", "queen", "quest", "quickly",
  "quiet", "quietly", "quit", "quite", "quote",
  
  "race", "racial", "radical", "radio", "rail", "railroad", "rain", "raise",
  "range", "rank", "rapid", "rapidly", "rare", "rarely", "rate", "rather", "rating",
  "ratio", "raw", "reach", "react", "reaction", "reader", "reading", "ready",
  "reality", "realize", "really", "realm", "rear", "reasonable", "recall",
  "receive", "recent", "recently", "recipe", "recognition", "recommend",
  "recommendation", "record", "recording", "recover", "recovery", "recruit",
  "red", "reduce", "reduction", "refer", "reference", "reflect", "reflection",
  "reform", "refugee", "refuse", "regard", "regarding", "regardless", "regime",
  "regional", "register", "regular", "regularly", "regulate", "regulation",
  "reinforce", "reject", "relate", "related", "relating", "relative", "relatively",
  "relax", "release", "relevant", "relief", "religion", "religious", "rely",
  "remain", "remaining", "remarkable", "remember", "remind", "remote", "remove",
  "repeat", "repeatedly", "replace", "reply", "reporter", "represent",
  "representation", "representative", "Republican", "reputation", "request",
  "require", "requirement", "rescue", "researcher", "resemble", "reservation",
  "resident", "resist", "resistance", "resolution", "resolve", "resort", "resource",
  "respect", "respond", "respondent", "response", "responsibility", "responsible",
  "rest", "restaurant", "restore", "restriction", "result", "retain", "retire",
  "retirement", "return", "reveal", "revenue", "review", "revolution",
  "revolutionary", "reward", "rhetoric", "rice", "rich", "rid", "ride", "right",
  "right", "ring", "rise", "rising", "risk", "ritual", "rival", "river", "road",
  "rock", "role", "roll", "romantic", "roof", "room", "root", "rope", "rose",
  "rough", "roughly", "round", "route", "routine", "row", "rub", "rule", "ruler",
  "running", "rural", "rush", "Russian",
  
  "sacred", "sacrifice", "sad", "safe", "safety", "sake", "salad", "salary",
  "salt", "same", "sample", "sanction", "sand", "satellite", "satisfaction",
  "satisfy", "sauce", "save", "saving", "scale", "scandal", "scared", "scenario",
  "scene", "schedule", "scheme", "scholar", "scholarship", "scientific", "scientist",
  "scope", "score", "scream", "script", "sea", "seal", "search", "season", "seat",
  "second", "secret", "secretary", "section", "sector", "secure", "security",
  "seed", "seek", "seem", "segment", "seize", "select", "selection", "self",
  "sell", "Senate", "senator", "send", "senior", "sensation", "sensitive",
  "sentence", "separate", "sequence", "series", "serious", "seriously", "servant",
  "serve", "session", "setting", "settle", "settlement", "seven", "seventeen",
  "seventh", "seventy", "several", "severe", "sexual", "shade", "shadow", "shake",
  "shall", "shape", "share", "sharp", "shatter", "shed", "sheet", "shelf", "shell",
  "shelter", "shift", "shine", "ship", "shirt", "shock", "shoe", "shoot", "shooting",
  "shopping", "shore", "shortly", "shot", "should", "shoulder", "shout", "show",
  "shower", "shrug", "shut", "sick", "side", "sigh", "sight", "sign", "signal",
  "significance", "significantly", "silence", "silent", "silver", "similar",
  "similarly", "simple", "simply", "sin", "since", "sing", "singer", "single",
  "sink", "sister", "site", "situation", "sixteen", "sixth", "sixty", "size",
  "ski", "skill", "skilled", "skin", "sky", "slave", "sleep", "slice", "slide",
  "slight", "slightly", "slip", "slow", "slowly", "small", "smart", "smell",
  "smile", "smoke", "smooth", "snap", "snow", "so", "so-called", "soccer", "social",
  "socialism", "socialist", "society", "soft", "software", "soil", "solar",
  "soldier", "solid", "solution", "solve", "somebody", "somehow", "someone",
  "something", "sometimes", "somewhat", "somewhere", "song", "sophisticated",
  "sorry", "sort", "soul", "sound", "soup", "source", "south", "southern",
  "Soviet", "space", "Spanish", "speak", "speaker", "special", "specialist",
  "species", "specific", "specifically", "speech", "speed", "spend", "spending",
  "spin", "spirit", "spiritual", "split", "spokesman", "sponsor", "sport",
  "spot", "spread", "spring", "square", "squeeze", "stability", "stable", "staff",
  "stage", "stair", "stake", "stand", "standard", "standing", "star", "stare",
  "start", "starting", "state", "statement", "station", "statistics", "status",
  "stay", "steady", "steal", "steel", "steep", "steer", "stem", "step", "stick",
  "still", "stir", "stock", "stomach", "stone", "stop", "storage", "store",
  "storm", "story", "straight", "strange", "stranger", "strategic", "strategy",
  "stream", "street", "strength", "strengthen", "stress", "stretch", "strike",
  "striking", "string", "strip", "stroke", "strong", "strongly", "structure",
  "struggle", "student", "studio", "study", "stuff", "stupid", "style", "subject",
  "submit", "subsequent", "substance", "substantial", "substantially", "succeed",
  "successful", "successfully", "such", "sudden", "suddenly", "sue", "suffer",
  "sufficient", "sugar", "suggest", "suggestion", "suicide", "suit", "summer",
  "summit", "super", "supply", "supporter", "suppose", "supposed", "Supreme",
  "sure", "surely", "surface", "surgery", "surprise", "surprised", "surprising",
  "surprisingly", "surround", "survey", "survival", "survive", "survivor",
  "suspect", "sustain", "swear", "sweep", "sweet", "swim", "swing", "switch",
  "symbol", "symptom", "system", "systematic",
  
  "table", "tablespoon", "tactic", "tail", "take", "tale", "talent", "tall",
  "tank", "tap", "tape", "target", "task", "taste", "tax", "taxpayer", "teach",
  "teaching", "team", "tear", "teaspoon", "technical", "technique", "technology",
  "teen", "teenager", "telephone", "telescope", "television", "tell", "temperature",
  "temporary", "ten", "tend", "tendency", "tennis", "tension", "tent", "term",
  "terms", "terrible", "territory", "testify",
  "testimony", "testing", "text", "than", "thank", "thanks", "theater", "their",
  "them", "theme", "themselves", "then", "theory", "therapy", "there", "therefore",
  "these", "they", "thick", "thin", "thing", "think", "thinking", "third",
  "thirteen", "thirty", "this", "those", "though", "thought", "thousand", "threat",
  "threaten", "three", "throat", "through", "throughout", "throw", "thus", "ticket",
  "tie", "tight", "time", "tiny", "tip", "tire", "tired", "tissue", "title",
  "tobacco", "today", "toe", "together", "tomato", "tomorrow", "tone", "tongue",
  "tonight", "tool", "tooth", "topic", "toss", "total", "totally", "touch",
  "tough", "tour", "tourist", "tournament", "toward", "towards", "tower", "town",
  "toy", "trace", "track", "trade", "tradition", "traditional", "traffic",
  "tragedy", "trail", "train", "training", "transfer", "transform", "transformation",
  "transition", "translate", "transportation", "trap", "trash", "travel", "treat",
  "treaty", "tree", "tremendous", "trend", "trial", "tribe", "trick", "trip",
  "troop", "trouble", "truck", "truly", "trust", "truth", "tube", "tunnel",
  "turn", "twelve", "twenty", "twice", "twin", "twist", "typical", "typically",
  
  "ugly", "ultimate", "ultimately", "unable", "uncle", "under", "undergo",
  "understand", "understanding", "unfortunately", "uniform", "union", "unique",
  "unit", "United", "universal", "universe", "university", "unknown", "unless",
  "unlike", "unlikely", "until", "unusual", "upon", "upper", "urban", "urge",
  "usage", "used", "useful", "user", "usual", "usually", "utility",
  
  "vacation", "valley", "valuable", "variable", "variation", "variety", "various",
  "vary", "vast", "vegetable", "vehicle", "venture", "version", "versus", "very",
  "vessel", "veteran", "via", "victim", "victory", "video", "view", "viewer",
  "village", "violate", "violation", "virtually", "virtue",
  "virus", "visible", "vision", "visit", "visitor", "visual", "vital", "voice",
  "volume", "volunteer", "vote", "voter", "vulnerable",
  
  "wage", "wait", "wake", "walk", "wall", "wander", "want", "warm", "warn",
  "warning", "wash", "waste", "watch", "wave", "way", "weak", "wealth", "wealthy",
  "wear", "weather", "wedding", "week", "weekend", "weekly", "weigh",
  "weight", "welcome", "welfare", "well", "west", "western", "wet", "what",
  "whatever", "wheel", "when", "whenever", "where", "whereas", "whether", "which",
  "while", "whisper", "white", "whole", "whom", "whose", "wide", "widely",
  "widespread", "wife", "wild", "will", "willing", "wind", "window", "wine",
  "wing", "winner", "winter", "wipe", "wire", "wisdom", "wise", "wish", "with",
  "withdraw", "within", "without", "witness", "woman", "wonder", "wonderful",
  "wood", "wooden", "word", "working", "works", "workshop", "worth", "would",
  "wound", "wrap", "write", "writer", "writing", "wrong",
  
  "yard", "yeah", "yellow", "yesterday", "yield", "young", "your", "yours",
  "yourself", "youth", "zone"
];

// Shuffle function to randomize word order
export function shuffleWords(words: string[]): string[] {
  const shuffled = [...words];
  for (let i = shuffled.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
  }
  return shuffled;
}

// Get a shuffled subset of words
export function getShuffledWords(count: number = 100): string[] {
  const shuffled = shuffleWords(WORD_BANK);
  return shuffled.slice(0, count);
}
